package gcode

import (
	"bufio"
	"encoding/base64"
	"io"
	"regexp"
	"strconv"
	"strings"
)

// Analysis contains everything extracted from a G-code file.
type Analysis struct {
	Slicer             string
	MaterialType       string
	MaterialColor      string
	PrintSettingsID    string
	PrinterSettingsID  string
	FilamentSettingsID string
	PrinterModel       string
	FilamentName       string
	FilamentGrams      *float64
	EstimatedSeconds   *int
	LayerHeight        *float64
	NozzleDiameter     *float64
	BedTemp            *float64
	NozzleTemp         *float64
	Thumbnail          *Thumbnail // PNG/JPG bytes if present
	Raw                map[string]string
}

// Thumbnail holds extracted thumbnail bytes and mime type.
type Thumbnail struct {
	MimeType string
	Data     []byte
}

// Analyze reads a G-code stream and returns structured metadata.
func Analyze(r io.Reader) (*Analysis, error) {
	a := &Analysis{Raw: map[string]string{}}
	scanner := bufio.NewScanner(r)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		lower := strings.ToLower(line)
		if !strings.HasPrefix(line, ";") {
			applyCommandFallback(a, line)
			continue
		}
		key, value := commentKeyValue(line)
		if key != "" && value != "" {
			a.Raw[key] = trimQuoted(value)
		}
		_ = lower

		switch {
		case strings.Contains(lower, "generated by") || strings.Contains(lower, "slicer"):
			a.Slicer = strings.Trim(strings.TrimPrefix(line, ";"), " ")
		case containsAny(lower, "filament used", "total filament used"):
			if v := firstFloat(line); v != nil {
				grams := *v
				a.FilamentGrams = &grams
			}
		case containsAny(lower, "estimated printing time", "estimated print time", "print time"):
			if secs := parseDurationSeconds(line); secs > 0 {
				a.EstimatedSeconds = &secs
			}
		case key == "filament_type" || key == "filament type":
			a.MaterialType = trimQuoted(value)
		case key == "print_settings_id":
			a.PrintSettingsID = trimQuoted(value)
		case key == "printer_settings_id":
			a.PrinterSettingsID = trimQuoted(value)
		case key == "filament_settings_id":
			a.FilamentSettingsID = trimQuoted(value)
			a.FilamentName = trimQuoted(value)
		case key == "printer_model":
			a.PrinterModel = trimQuoted(value)
		case (key == "filament_name" || key == "filament name" || key == "default_filament_profile") && a.FilamentName == "":
			a.FilamentName = trimQuoted(value)
		case key == "layer_height" || key == "layer height":
			a.LayerHeight = firstFloat(value)
		case key == "nozzle_diameter" || key == "nozzle diameter":
			a.NozzleDiameter = firstFloat(value)
		case key == "bed_temperature" || key == "bed temperature":
			a.BedTemp = firstFloat(value)
		case (key == "nozzle_temperature" || key == "nozzle temperature" || key == "temperature") && a.NozzleTemp == nil:
			a.NozzleTemp = firstFloat(value)
		case strings.Contains(lower, "thumbnail begin"):
			if thumb := extractThumbnail(scanner); thumb != nil {
				a.Thumbnail = thumb
			}
		}
	}
	return a, scanner.Err()
}

// extractThumbnail decodes a Cura/Prusa/Orca base64 thumbnail block.
func extractThumbnail(scanner *bufio.Scanner) *Thumbnail {
	var mime string
	var b64 strings.Builder
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		lower := strings.ToLower(line)
		if strings.Contains(lower, "thumbnail end") {
			break
		}
		if mime == "" {
			if strings.Contains(lower, "png") {
				mime = "image/png"
			} else if strings.Contains(lower, "jpg") || strings.Contains(lower, "jpeg") {
				mime = "image/jpeg"
			}
		}
		clean := strings.TrimPrefix(line, ";")
		clean = strings.TrimSpace(clean)
		b64.WriteString(clean)
	}
	data, err := decodeBase64(b64.String())
	if err != nil || len(data) == 0 {
		return nil
	}
	if mime == "" {
		mime = detectImageMime(data)
	}
	return &Thumbnail{MimeType: mime, Data: data}
}

// Helpers --------------------------------------------------------------------

var floatRe = regexp.MustCompile(`[-+]?\d*\.?\d+`)

func applyCommandFallback(a *Analysis, line string) {
	upper := strings.ToUpper(strings.TrimSpace(line))
	if strings.Contains(upper, "BED_TEMP=") {
		if v := namedParameter(upper, "BED_TEMP"); v != nil {
			a.BedTemp = v
		}
	}
	if strings.Contains(upper, "EXTRUDER_TEMP=") {
		if v := namedParameter(upper, "EXTRUDER_TEMP"); v != nil {
			a.NozzleTemp = v
		}
	}
	if strings.HasPrefix(upper, "M104") || strings.HasPrefix(upper, "M109") {
		if v := sParameter(upper); v != nil {
			a.NozzleTemp = v
		}
	}
	if strings.HasPrefix(upper, "M140") || strings.HasPrefix(upper, "M190") {
		if v := sParameter(upper); v != nil {
			a.BedTemp = v
		}
	}
}

func sParameter(line string) *float64 {
	parts := strings.Fields(line)
	for _, part := range parts {
		if strings.HasPrefix(part, "S") && len(part) > 1 {
			v, err := strconv.ParseFloat(strings.TrimPrefix(part, "S"), 64)
			if err == nil {
				return &v
			}
		}
	}
	return nil
}

func namedParameter(line, name string) *float64 {
	parts := strings.Fields(line)
	for _, part := range parts {
		if strings.HasPrefix(part, name+"=") {
			v, err := strconv.ParseFloat(strings.TrimPrefix(part, name+"="), 64)
			if err == nil {
				return &v
			}
		}
	}
	return nil
}

func firstFloat(s string) *float64 {
	m := floatRe.FindString(s)
	if m == "" {
		return nil
	}
	v, err := strconv.ParseFloat(m, 64)
	if err != nil {
		return nil
	}
	return &v
}

func commentKeyValue(line string) (string, string) {
	clean := strings.TrimSpace(strings.TrimPrefix(line, ";"))
	parts := strings.SplitN(clean, "=", 2)
	if len(parts) == 1 {
		parts = strings.SplitN(clean, ":", 2)
	}
	if len(parts) != 2 {
		return strings.ToLower(strings.TrimSpace(clean)), ""
	}
	return strings.ToLower(strings.TrimSpace(parts[0])), strings.TrimSpace(parts[1])
}

func trimQuoted(s string) string {
	return strings.Trim(strings.TrimSpace(s), `"`)
}

func settingFloat(s string) *float64 {
	value := valueAfterSeparator(s)
	if value != "" {
		return firstFloat(value)
	}
	return firstFloat(s)
}

func valueAfterSeparator(s string) string {
	parts := strings.SplitN(s, "=", 2)
	if len(parts) == 1 {
		parts = strings.SplitN(s, ":", 2)
	}
	if len(parts) == 2 {
		return strings.Trim(strings.TrimPrefix(parts[1], ";"), " \t")
	}
	return ""
}

func parseDurationSeconds(s string) int {
	lower := strings.ToLower(s)
	total := 0
	patterns := []struct {
		re   *regexp.Regexp
		mult int
	}{
		{regexp.MustCompile(`(\d+)\s*d`), 86400},
		{regexp.MustCompile(`(\d+)\s*h`), 3600},
		{regexp.MustCompile(`(\d+)\s*m`), 60},
		{regexp.MustCompile(`(\d+)\s*s`), 1},
	}
	for _, p := range patterns {
		for _, m := range p.re.FindAllStringSubmatch(lower, -1) {
			v, _ := strconv.Atoi(m[1])
			total += v * p.mult
		}
	}
	return total
}

func containsAny(s string, subs ...string) bool {
	for _, sub := range subs {
		if strings.Contains(s, sub) {
			return true
		}
	}
	return false
}

func detectImageMime(data []byte) string {
	if len(data) >= 8 && string(data[:8]) == "\x89PNG\r\n\x1a\n" {
		return "image/png"
	}
	if len(data) >= 3 && data[0] == 0xff && data[1] == 0xd8 && data[2] == 0xff {
		return "image/jpeg"
	}
	return "image/png"
}

func decodeBase64(s string) ([]byte, error) {
	s = strings.TrimSpace(s)
	if strings.Contains(s, ",") {
		parts := strings.SplitN(s, ",", 2)
		s = parts[1]
	}
	if data, err := base64.StdEncoding.DecodeString(s); err == nil {
		return data, nil
	}
	return base64.RawStdEncoding.DecodeString(s)
}
