package gcode

import (
	"strings"
	"testing"
)

func TestAnalyze_ExtractsCommonMetadata(t *testing.T) {
	input := `; generated by OrcaSlicer 2.0
; filament_type = PLA
; filament_color = #ff0000
; filament_settings_id = "PLA MODIFICADO_pf1"
; filament used [g] = 42.5
; estimated printing time (normal mode) = 1h 2m 3s
; layer_height = 0.2
; nozzle_diameter = 0.4
M104 S220
M140 S60
G1 X10 Y10 E1
`
	analysis, err := Analyze(strings.NewReader(input))
	if err != nil {
		t.Fatal(err)
	}
	if analysis.Slicer == "" {
		t.Fatal("expected slicer")
	}
	if analysis.MaterialType != "PLA" {
		t.Fatalf("material type = %q", analysis.MaterialType)
	}
	if analysis.MaterialColor != "" {
		t.Fatalf("material color = %q", analysis.MaterialColor)
	}
	if analysis.FilamentName != "PLA MODIFICADO_pf1" {
		t.Fatalf("filament name = %q", analysis.FilamentName)
	}
	if analysis.FilamentGrams == nil || *analysis.FilamentGrams != 42.5 {
		t.Fatalf("filament grams = %#v", analysis.FilamentGrams)
	}
	if analysis.EstimatedSeconds == nil || *analysis.EstimatedSeconds != 3723 {
		t.Fatalf("estimated seconds = %#v", analysis.EstimatedSeconds)
	}
	if analysis.NozzleTemp == nil || *analysis.NozzleTemp != 220 {
		t.Fatalf("nozzle temp = %#v", analysis.NozzleTemp)
	}
	if analysis.BedTemp == nil || *analysis.BedTemp != 60 {
		t.Fatalf("bed temp = %#v", analysis.BedTemp)
	}
}

func TestAnalyze_ExtractsThumbnail(t *testing.T) {
	input := `; thumbnail begin 1x1 68
; iVBORw0KGgo=
; thumbnail end
`
	analysis, err := Analyze(strings.NewReader(input))
	if err != nil {
		t.Fatal(err)
	}
	if analysis.Thumbnail == nil {
		t.Fatal("expected thumbnail")
	}
	if analysis.Thumbnail.MimeType != "image/png" {
		t.Fatalf("mime = %q", analysis.Thumbnail.MimeType)
	}
	if len(analysis.Thumbnail.Data) == 0 {
		t.Fatal("expected thumbnail data")
	}
}
